# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MONGODB_URI_LOCAL: $(MONGODB_URI_LOCAL)
  SESSION_SECRET: $(SESSION_SECRET)
  FACEBOOK_ID: $(FACEBOOK_ID)
  FACEBOOK_SECRET: $(FACEBOOK_SECRET)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: echo 'ECHO MY VARIABLE'
- bash: echo $(MONGODB_URI_LOCAL)

- script: |
    npm install
    npm test
  displayName: 'npm install and test'
