# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  env:
    MONGODB_URI_LOCAL: $(MONGODB_URI_LOCAL)
    SESSION_SECRET: $(SESSION_SECRET)
    FACEBOOK_ID: $(FACEBOOK_ID)
    FACEBOOK_SECRET: $(FACEBOOK_SECRET)

- bash: echo 'ECHO MY VARIABLE'
- bash: echo $(FACEBOOK_ID)

- script: |
    npm install
    echo %MONGODB_URI_LOCAL% env: MONGODB_URI_LOCAL: $(MONGODB_URI_LOCAL)
    echo %SESSION_SECRET% env: SESSION_SECRET: $(SESSION_SECRET)
    echo %FACEBOOK_ID% env: FACEBOOK_ID: $(FACEBOOK_ID)
    echo %FACEBOOK_SECRET% env: FACEBOOK_SECRET: $(FACEBOOK_SECRET)
    npm test
  displayName: 'npm install and test'
